engines:
  duplication:
    enabled: false
  eslint:
    config:
      config: .eslintrc.js
    enabled: true
  fixme:
    enabled: true
ratings:
  exclude_paths:
    - "**.spec.js"
  paths:
    - "**.js"