engines:
  duplication:
    enabled: false
  eslint:
    enabled: true
    config: './.eslintrc.js'
  fixme:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
exclude_paths:
- "**.spec.js"
