engines:
  duplication:
    enabled: false
  eslint:
    enabled: true
    config:
      config: "./.eslintrc.js"
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  exclude_paths:
- "**.spec.js"
